# -*- coding: utf-8 -*-
"""graphs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hPiRi3y0KbVze2XVU0VTxyIjjI0zUMrJ
"""

import matplotlib.pyplot as plt
hours = [1,2,3,4,5,6,7,8]
visitors = [50,60,70,80,120,130,140,150] # Added a value to match the length of 'hours'
plt.plot(hours,visitors,
         color = "green",
         marker ="o",
         linestyle ="-", # Corrected linestyle from '_' to '-'
         linewidth =1,
         alpha =1,
         label = "visitors") # Corrected 'lable' to 'label'
plt.title("website visitors per Hour")
plt.xlabel("Hour of Day")
plt.ylabel("number of visitors") # Corrected 'ylable' to 'ylabel'
plt.legend()
plt.grid(True,linestyle="--",alpha =0.5)
plt.show()

import matplotlib.pyplot as plt
products = ['Laptop', 'Mobile', 'Tbalet', 'Headphones', 'SmartWatch']
sales = [250, 400, 150, 300, 180]

plt.bar(products, sales, color='red', edgecolor='black', alpha=0.5, width=0.8)
plt.title("Product Saless Comparison")
plt.xlabel("Products")
plt.ylabel("Units Sold")
plt.show()

import matplotlib.pyplot as plt
marks = [45, 55, 60, 73, 68, 56 ,78, 46, 89, 45, 78, 90, 92, 56, 68, 69, 76, 86, 93, 45, 56, 77, 88, 99]

plt.hist(marks, bins= 6, histtype='bar', color='lightblue', edgecolor='green', density=False)
plt.title("Distrubution of Student Marks")
plt.xlabel("Marks Range")
plt.ylabel("Numbero of Students")
plt.show()

import matplotlib.pyplot as plt
brands = ["Apple", "Samsung", "Xiaomi", "Oppo", "Others"]
market_share = [30, 25, 20, 10, 15]
plt.pie(market_share,
        labels=brands,
        autopct="%.2f%%",
        startangle=90,
        colors=["gold", "red", "lightcoral", "green", "blue"],
        explode=[0.1, 0, 0, 0, 0],
        shadow=True)
plt.title("Mobile Market Share 2025")
plt.show()

import matplotlib.pyplot as plt

ad_spend = [2, 4, 5, 7, 8, 10, 11, 12]
sales = [27, 25, 28, 35, 40, 48, 50, 52]
profit = [200, 250, 90, 350, 40, 80, 500, 520]
colors = [8,1,2,3,5,6,7,4]

plt.scatter(ad_spend, sales,
            s=profit,
            c=colors,
            cmap='Reds',
            alpha=0.8,
            edgecolors='black',
            linewidths=1.2
           )

plt.title("Advertising Spend vs Sales (with Color & Size)", fontsize=14, fontweight="bold")
plt.xlabel("Ad Spend ($1000s)", fontsize=12)
plt.ylabel("Sales ($1000s)", fontsize=12)

plt.colorbar(label="Sales Value")

plt.grid(True, linestyle="--", alpha=0.2)
plt.show()

import matplotlib.pyplot as plt

scores = [
    [ 70, 85, 90, 92, 88, 76, 95,9],
    [65, 70, 68, 72, 75, 80, 85, 78],
    [90, 92, 94, 96, 88, 91, 89, 93],
    [62, 60, 61, 90, 65, 63, 67, 61],
    [70, 85, 8, 50, 92, 91, 100, 89]
]
plt.boxplot(scores,
            patch_artist=True,
            medianprops=dict(color="blue", linewidth=2),
            whiskerprops=dict(color="red"),
            capprops=dict(color="green"),
            notch=True,
            vert=False,
            labels=["A", "B", "C", "D", "E"])

plt.title("Exam Scores Distribution Across Classes")
plt.xlabel("Classes")
plt.ylabel("Scores")
plt.grid(True, linestyle="--", alpha=0.7)

plt.show()

import matplotlib.pyplot as plt

days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
visitors = [120, 150, 170, 200, 180, 220, 250]

plt.fill_between(days, visitors,
                 color="skyblue", alpha=0.5,
                 label="Website Visitors")

plt.plot(days, visitors, color="red", linewidth=1)
plt.title("Website Visitors Over a Week")
plt.xlabel("Day of Week")
plt.ylabel("Number of Visitors")
plt.legend()
plt.grid(True, linestyle="--", alpha=0.6)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

data = np.array([
    [30, 32, 31, 29, 28, 27, 26],
    [33, 34, 32, 30, 29, 28, 27],
    [35, 36, 34, 33, 31, 30, 29],
    [37, 38, 35, 34, 32, 31, 30],
    [36, 37, 34, 32, 31, 30, 29]
])

days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

weeks = ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5"]

sns.heatmap(data,
            annot=True,
            fmt=".2f",
            cmap="YlOrRd",
            linewidths=0.5,
            xticklabels=days,
            yticklabels=weeks)

plt.title("Weekly Temperature Heatmap", fontsize=14, fontweight="bold")
plt.xlabel("Days of the Week")
plt.ylabel("Weeks")
plt.show()

import matplotlib.pyplot as plt

days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
sales = [120, 135, 150, 160, 170, 200, 220]
profit = [30, 40, 45, 50, 55, 70, 80]

plt.figure(figsize=(10, 8))

plt.subplot(2, 2, 1)
plt.plot(days, sales, marker="o", color="blue")
plt.title("Sales Over Days")
plt.grid(True)

plt.subplot(2, 2, 2)
plt.bar(days, sales, color="orange")
plt.title("Sales Bar Chart")

plt.subplot(2, 2, 3)
plt.scatter(sales, profit, color="green", s=100, edgecolors="black")
plt.title("Sales vs Profit")

plt.subplot(2, 2, 4)
plt.pie(sales, labels=days, autopct="%1.1f%%", startangle=90)
plt.title("Sales Distribution")

plt.tight_layout()
plt.show()