# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1My_Y_pdfbTBSiuVu4Z00Dz5yj4yluuIw
"""

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print("One dimensional array:", arr1, sep='\n', end='\n\n')

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Two dimensional array:", arr2, sep='\n', end='\n\n')

arr3 = np.array([[[1, 2], [3,4]], [[5, 6], [7, 8]]])
print("Three dimensional array:", arr3, sep='\n', end='\n\n')

zeros = np.zeros((3, 4))
print("zeros_5:", zeros)

ones = np.ones((3, 4))
print("zeros_7:", ones)

identity = np.eye(4)
print(identity)

fullarray = np.full((10, 2), 20)
print(fullarray)

range_arr = np.arange(10, 0, -1)
print(range_arr)

range_arr = np.arange(2, 51, 2)
print(range_arr)

lin_space = np.linspace(0, 10, 5)
print(lin_space)

lin_space = np.linspace(0, 100, 5)
print(lin_space)

rand_arr = np.random.randint(100)
print(rand_arr)

np.random.seed(45)
random_arr = np.random.randint(200)
print(random_arr)

rand_float = np.random.rand()
print(rand_float)

rand_float = np.random.rand(4)
print(rand_float)

rand_int = np.random.randint(1,6,(4,3))
print(rand_int)

rand_int = np.random.randint(1,6,8)
print(rand_int)

l=['html','css','javascript','python','mysql']
rand_choice = np.random.choice(l,3)
print(rand_choice)

arr = np.array([[1,2],[4,5],[6,7],[8,7],[1,2],[4,5]])
print(arr.shape)

reshaped = arr.reshape(3,4)
print(reshaped)

a=np.array([[1,2,3,4],[1,2,3,4]])
flattened =a.flatten()
print(flattened)

transposed = arr.T
print(transposed)

arr = np.array([10,23,45,66])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[:3])
print(arr[::2])

import numpy as np
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matrix[0:3,1])
print(matrix[1:3,2])
print(matrix[0:2,0:2])
print(matrix[1:3,1:3])

arr = np.array([4,8,90,34,36])

print(arr+10)
print(arr*2)
print(arr**0.5)

print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))

print(np.mean(a))
print(np.var(a))
print(np.std(a))

print(np.min(arr))
print(np.max(arr))

arr = np.array([1,2,3,4,4,5,5,6,4,7])
print(arr%2==0)
print(arr[arr%2!=0])

arr = np.array([3,1,4,5,6,7])
sorted_arr = np.sort(arr)
print(sorted_arr)

unique_vals = np.unique(arr)
print(unique_vals)

arr = np.array([1,2,3])
view_arr = arr.view()
view_arr[0] = 100
print(view_arr)
print(arr)

copy_arr = arr.copy()
copy_arr[0] = 10
print(copy_arr)
print(arr)

A = np.array([[1,3],[3,4]])
B = np.array([[5,6],[7,8]])
print(np.dot(A,B))

print(np.linalg.det(A))

eigenvalues,eigenvectors = np.linalg.eig(A)
print(eigenvalues)

print(eigenvectors)

c = np.array([5,11])
solution = np.linalg.solve(A,c)
print(solution)

A = np.array ([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
vertical_stack = np.vstack((A,B))
horizontal_stack = np.hstack((A,B))
print(vertical_stack)
print(horizontal_stack)