# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NKujBtbDYUmcjgTnZFKaKQQl5ilK3Sqe
"""

pip install pandas

import pandas as pd
prices = [2999, 15999, 52999, 4999, 1999]
products = ["Wireless Earbuds", "Smartphones", "Laptop", "Smartwatch", "Bluetooth speaker"]
products_prices = pd.Series(prices,index=products)
print(products_prices)

print("Mean:",products_prices.mean())
print("Sum:",products_prices.sum())
print("Maximum:",products_prices.max())
print("Minimum:",products_prices.min())

print("Head (First 3 elements):\n", products_prices.head(3))
print("Tail (First 2 elements):\n", products_prices.tail(2))

print("Apply (Adding 18% GST):\n", products_prices.apply(lambda x: f"${x+(x*0.18)}"))
print("Map (Formatting as Currency):\n", products_prices.map(lambda x: f"${x}.00"))

print("Values Counts:\n", products_prices.value_counts())

