# -*- coding: utf-8 -*-
"""WebScraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J_f_fCpcoPBNFM0NhBycT9YAS4tnAynw
"""

#Loading required libraries
import requests
from bs4 import BeautifulSoup

URL = 'https://codegnan.com/'

# Loading the webpage in memory using requests library
page = requests.get(URL)

# Check the status Code of the Page
page.status_code

htmlcode = page.text
print(htmlcode)

soup = BeautifulSoup(htmlcode, 'html.parser')
print(soup)

title = soup.title.text
print("website Title:",title)

headings = soup.find_all("h3")
for heading in headings:
  print(heading.text.strip())

links = soup.find_all("a")
for link in links[:10]:...#First.10.links
print(link.get("href"))

images = soup.find_all("img")
for image in images[:10]:
  print(image.get("src"))

description = soup.find("meta", attrs={"name":"description"})
if description:
  print("Description:")
  print(description.get("content"))

for tag in soup.find_all():
  if tag.get("class"):
    print(tag.get("class"))

scripts = soup.find_all("script")
for script in scripts:
  print(script.get("src"))

logo = soup.find("img")
print(logo.get("src"))

og_image = soup.find("meta",property = "og:image")
print(og_image["content"])

menus = soup.find_all("li")
for menu in menus[:20]:
  print(menu.text.strip())

paragraphs = soup.find_all("p")
for p in paragraphs[:10]:
  print(p.text.strip())

buttons=soup.find_all("button")
for button in buttons:
  print(button.text.strip())