from datetime import date,time,datetime,timedelta

today = date.today()
print (today)
print (today.day)
print(today. month)
print(today.year)
print(today.weekday())


t = time(23,6,5)
print(t.hour)
print(t.minute)
print(t.secound)
n = datetime.now()
print(n)
print(n.strftime('%d-%m-%y'))
print(n.strftime('%D-%m-%Y %H:%M:%S'))
print(n.strftime('%D-%m-%Y %H:%M:%S %p'))
print(n.strftime('%d %b %Y %H:%M:%S %p'))
print(n.strftime('%d %B %Y %H:%M:%S %p'))
print(n.strftime('%a %d %Y %H:%M:%S %p'))
print(n.strftime('%A %d %Y %H:%M:%S %p'))

n= datetime.now()
print(n)
print(n.day)
print(n.month)
print(n.year)
print(n.weekday())
print(n.hour)
print(n.minute)
print(n.seconds)


t= date.today()
n= datetime.now()
t7 = t+ timedelta(days = 7)
t5 = t - timedelta(days =7)
n15 = n + timedelta (days = 7)
print(t,t7,t5)
print(n,n15)